name: fuel_delivary_app_admin
description: "Admin side application of a Vechile service App"


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  gap: ^3.0.1
  google_fonts: ^6.2.1
  get: ^4.6.6
  firebase_core: ^3.8.1
  firebase_dart: ^1.2.3
  cloud_firestore: ^5.5.1
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.6
  firebase_storage: ^12.3.7
  flex_color_scheme: ^8.1.0
  awesome_dialog: ^3.2.1
  firebase_auth: ^5.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  
  fonts:
    - family: Lexend
      fonts:
        - asset: fonts/Lexend-VariableFont_wght.ttf
  
  
    - family: Lexend-Bold
      fonts:
        - asset: fonts/Lexend-Bold.ttf
  
    - family: Poppins
      fonts:
        - asset: fonts\Poppins-Black.ttf

  
  
  
  
